version: '3'
services:

  ################
  # Torrent server
  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./.deluge/config:/config
      - ./storage/done/:/storage/done/
      - ./storage/todo/:/storage/todo/
      - ./storage/progress/:/storage/progress/
      - ./storage/torrents/:/storage/torrents/
    network_mode: host

  ##############
  # Samba server
  samba:
    container_name: samba
    hostname: samba
    image: sixeyed/samba
    volumes:
      - ./storage/:/mnt/storage/
    ports:
      - "139:139"
      - "446:445"
      - "137:137/udp"
      - "138:138/udp"
    command: samba.sh -s "storage;/mnt/storage;yes;no;yes;all"
    deploy:
      resources:
        limits:
          memory: 1G
    restart: always

  ################
  # Plex media server
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - ./.plex:/config
#      - /path/to/tvseries:/tv
#      - /path/to/movies:/movies
      - ./storage/done/_Video/TVShows:/tv
      - ./storage/done/_Video/Films:/movies
    restart: unless-stopped